[book]
authors = [""]
language = "en"
multilingual = false
src = "src"
title = "Elemente de Informatica Mobila ğŸŒ"

[build]
build-dir = "public"

[output.html]
additional-css = ["./assets/custom.css", "tabbed-code-blocks.css"]
additional-js = ["tabbed-code-blocks.js"]
git-repository-url = "https://gitlab.cs.pub.ro/eim/eim.pages.upb.ro"
edit-url-template = "https://gitlab.cs.pub.ro/eim/eim.pages.upb.ro/edit/master/{path}"
no-section-label = true
default-theme = "Light"

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]

[output.html.fold]
enable = true
level = 0
